### PR TITLE
Auto publish to PyPI, Github release and docs on tag

### LINKED ISSUE #64: Fix release process
Will need to accomodate the new packages structure. Involves editing the .github workflow.

### LINKED ISSUE #81: Automatic doc building
Currently the docs deployment is a manual `mkdocs gh-deploy`. This could be set up in GitHub actions.

### PR DESCRIPTION
**Pull request by multimeric**
Closes #81, closes #64

### CODE REVIEW

**Comment by multimeric** [comment]
Hi @pr4deepr, can you please ensure that:

* There is a secret called `TWINE_TOKEN` associated with this repo. Should be configurable [here](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/settings/secrets/actions)
* The `GITHUB_TOKEN` has write permission. Should be [configured here](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/settings/actions#:~:text=Workflow%20permissions)

This will give the workflow the permissions to push a release.

**Comment by pr4deepr** [comment]
> * There is a secret called `TWINE_TOKEN` associated with this repo which stores a PyPI token that has push permissions to both `napari_lattice` and `lls_core`. Should be configurable [here](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/settings/secrets/actions)

There is a Twine token for the repo which I've used for automatic deployment to pypi before. 


> * The `GITHUB_TOKEN` has write permission. Should be [configured here](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/settings/actions#:~:text=Workflow%20permissions)

Workflow permissions have: Read and Write permissions enabled.

**Comment by multimeric** [comment]
Okay great. The only issue is that it might not have permissions to push the `lls_core` package, because it doesn't exist yet. Anyway, once the other issues are fixed, I'll merge this and we can test out a release. It might not work the first time.

**Comment by multimeric** [comment]
Okay, this looks good. We'll have to merge this and then I'll push some tags directly to the repo in order to run the actual deployment. It probably won't work the first time but that's not a big deal.

**Comment by pr4deepr** [comment]
Thanks, just checking that updating docs will only trigger a docs specific workflow to update the site??

**Comment by multimeric** [comment]
Oh yeah true, there's no reason to limit the docs to only building when a new release is made

**Comment by multimeric** [comment]
Okay, I think this is failing to push the docs just because you haven't granted permissions for pull requests to do that, which is a good practice:
image

So this should work once this is merged.

**Review by pr4deepr — APPROVED** [review]

**Pull request merged**
