### PR TITLE
Orthogonal interpolation

### PR DESCRIPTION
**Pull request by pr4deepr**
Creating a pull request for the orthogonal interpolation.  Not merging it yet.

@haesleinhuepf , the new pyclesperanto deskew seems to be working, but we're testing it on some of our datasets to be sure. 
Till then, I have some questions about best pracrices with my code..
To get access to the "Deskew Direction" enum, I've imported it from pyclesperanto in the `init `file. Is this the right way to do this?
https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/blob/5237c2919c63ec7def5009daadf97173580e7c17/src/napari_lattice/__init__.py#L10

After this initialization, I access it from modules using an import like this:
https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/blob/5237c2919c63ec7def5009daadf97173580e7c17/src/napari_lattice/llsz_core.py#L12

Cheers
Pradeep

### CODE REVIEW

**Comment by pr4deepr** [comment]
Also, I've added more tests and fixed the [github test_and_deploy actions file](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/blob/orthogonal_interpolation/.github/workflows/test_and_deploy.yml)..

**Comment by DrLachie** [comment]
I've added a bunch of changes to account for the change to enum classes with the importing of parameters from the config yml file. So far it looks like it should all work.

**Comment by pr4deepr** [comment]
Tests to add:

- [ ] tests for running deskewing using config yaml file
- [ ] tests for running deconvolution using config yaml file
- [ ] tests for running cropping and workflow using config yaml file

**Comment by haesleinhuepf** [comment]
> To get access to the "Deskew Direction" enum, I've imported it from pyclesperanto in the `init `file. Is this the right way to do this?

Hm. Actually this is supposed to be an internal thing, that's why it has an underscore `_` in the name.

Why don't you just use `cle.deskew_x` and `cle.deskew_y`? If these do not fulfill your use-case, we should change them.

**Comment by pr4deepr** [comment]
Ok, I'll create a github issue on pyclesperanto-prototype repo..

**Review by DrLachie — DISMISSED** [review]
Looks good as far as my testing went

**Comment by pr4deepr** [comment]
Sorry, didn't mean to dismiss your review. I just bumped the version number... 
😄 
I'll merge it now. 
Will work on this issue with Robert: https://github.com/clEsperanto/pyclesperanto_prototype/issues/238 in a separate branch..

**Pull request merged**
