### PR TITLE
Better conversion from napari Shapes to Rois

### LINKED ISSUE #63: Small ROI Bug
Just adding this so I don't forget. Small ROI issue:

Screen Shot 2024-08-23 at 1 31 17 pm

I think this is because the set of 2 ROIs are being treated as 1 ROI in this scenario where the user uploads a ZIP file. Should be an easy fix

### PR DESCRIPTION
**Pull request by multimeric**
Closes #63.

### CODE REVIEW

**Comment by multimeric** [comment]
Some manual verification would be great here, because although it doesn't throw an error anymore, I want to be sure that it's producing the correct output.

**Comment by pr4deepr** [comment]
The error doesn't happen but the coordinates are incorrect. 
They are in scaled `micron` space and not in pixels anymore.. 

It needs to be transformed in x and y by dividing by dx or dy

For example, if I look at an ROI and view the coordinates in napari, I get:

> [array([[206.17889806, 132.66785635],
>         [206.17889806, 163.98616998],
>         [240.97702431, 163.98616998],
>         [240.97702431, 132.66785635]])]

~Actual cropped image shape: (150, 35, 31)

but, this is scaled in microns. The actual coordinate should be divided by deskew.dy so the coordinates are in pixels (as in the previous code). The values should actually be:

> array([[1421.92343489,  914.95073342],
>        [1421.92343489, 1130.93910328],
>        [1661.91051251, 1130.93910328],
>        [1661.91051251,  914.95073342]])

~ Actual cropped image shape: (150,216,240)
If I run the cropping, I get a really tiny image.

**Comment by multimeric** [comment]
Thanks, should be fixed now.

**Comment by pr4deepr** [comment]
Cropping works fine in the plugin. 
However, now, if I select an ROI in the plugin:

image

and run the cropping, its always the first ROI in the list that gets processed. In the earlier
First ROI in the list is highlighted by a red box below and the processed ROI is the green image on the top

image

**Comment by multimeric** [comment]
I don't follow. Is the selected shape supposed to impact cropping?

**Comment by multimeric** [comment]
TODO:
* [ ] Modify the ROI selector to list all shapes from all layers, rather than just listing shape layers
* [ ] Synchronise the shape selection with the ROI box
* [ ] Warn user in the preview box if multiple ROIs are selected

**Comment by multimeric** [comment]
Splitting the shape selection issue into a separate PR.

**Pull request merged**
