### PR TITLE
Fix #66

### LINKED ISSUE #66: crop with workflow processing only first ROI
CLI:

When running Crop in CLI by passing an ROIlist as a zip file and specifying roi_subset in yaml-config, I can save multiple ROIs. 

However, if I run this with a workflow, the workflow gets executed but only for the first ROI. Rest of the ROIs or crops do not get processed.

@multimeric

### PR DESCRIPTION
**Pull request by multimeric**
Changes:

* `WorkflowSlices.process()` now yields `ProcessedWorkflowOutput`, a new class that captures various metadata such as the output index. Previously it returned a `tuple[int, DataFrame | Path]` This is a breaking change since the API has changed.
* Integrated the regions of interest to make `iter_slices()` a triple loop. This means that cropping automatically works with workflows with no extra code paths.
* Added a new `progress_bar` option to `LatticeData`, that can be used to globally disable the progress bars. This is needed to ensure the workflow progress bar works correctly

Fixes #66.

### CODE REVIEW

**Comment by pr4deepr** [comment]
Thanks for this.. 
This seems to be working.. A few fixes:

- The ROI number in the progress bar output doesn't change. In example below, I am processing 4 ROIs, and its stuck at ROI: 0 until it reaches the end where it says ROI 4. Shouldn't that be ROI 3 instead?:
```
Timepoints:   0%|                                                                                               | 0/1 [00:08<?, ?it/s]
ROI: 0it [00:08, ?it/s]                                                                                         | 0/3 [00:00<?, ?it/s]
Timepoints:   0%|                                                                                               | 0/1 [00:08<?, ?it/s]
ROI: 0it [00:08, ?it/s]███████████████████████                                                          | 1/3 [00:13<00:27, 13.72s/it]
Timepoints:   0%|                                                                                               | 0/1 [00:08<?, ?it/s]
ROI: 0it [00:08, ?it/s]████████████████████████████████████████████████████                             | 2/3 [00:26<00:13, 13.30s/it]
Timepoints: 100%|███████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:39<00:00, 13.27s/it]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]                                                                                         | 0/3 [00:00<?, ?it/s]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]███████████████████████                                                          | 1/3 [00:07<00:14,  7.36s/it]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]████████████████████████████████████████████████████                             | 2/3 [00:14<00:07,  7.47s/it]
Timepoints: 100%|███████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:22<00:00,  7.38s/it]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]                                                                                         | 0/3 [00:00<?, ?it/s]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]███████████████████████                                                          | 1/3 [00:07<00:14,  7.27s/it]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]████████████████████████████████████████████████████                             | 2/3 [00:14<00:07,  7.35s/it]
Timepoints: 100%|███████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:22<00:00,  7.34s/it]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]                                                                                         | 0/3 [00:00<?, ?it/s]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]███████████████████████                                                          | 1/3 [00:07<00:14,  7.45s/it]
Timepoints:   0%|                                                                                               | 0/1 [00:02<?, ?it/s]
ROI: 0it [00:02, ?it/s]████████████████████████████████████████████████████                             | 2/3 [00:14<00:07,  7.35s/it]
Timepoints: 100%|███████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:21<00:00,  7.24s/it]
ROI: 4it [01:45, 26.42s/it]█████████████████████████████████████████████████████████████████████████████| 3/3 [00:21<00:00,  7.18s/it]
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
Processing successful. Results can be found in
```
In the config, I defined roi subset as  -> `roi_subset: [0,1,2,3]`
    
In the outputs, the images saved had the suffix, ROI_0 to ROI_3. 

- In this workflow I had some measurements saved as csv which worked, but the name of the output file has an extra number I don't recognize.
  In this example, csv files get saved as:
    - filename_deskewed_output_0_ROI_0.csv
    - filename_deskewed_output_3_ROI_1.csv
    - filename_deskewed_output_6_ROI_2.csv
    - filename_deskewed_output_9_ROI_3.csv
I'm not sure what the number after output means? i.e., output_0 etc...

Cheers
Pradeep

**Comment by multimeric** [comment]
> The ROI number in the progress bar output doesn't change. In example below, I am processing 4 ROIs, and its stuck at ROI: 0 until it reaches the end where it says ROI 4. Shouldn't that be ROI 3 instead?:

I've reworked the progress bar in a few ways. Hopefully it fixes your issue:

* Added a `total` to the ROIs
* Set the position of each bar
* When cropping, clear the channel and time bars once a ROI is completed
* Disable the progress bar for the workflow itself, which avoids duplicated progress bars

> In this workflow I had some measurements saved as csv which worked, but the name of the output file has an extra number I don't recognize.

The number in the filename refers to the index in the output tuple. There was previously a bug such that this number was wrong when cropping was enabled. Here is an example taken from one of the tests. We have a workflow that returns `image, some_dict, some_list, some_int`, and that results in:

- `RBC_tiny_deskewed_ROI_0.h5`: image for ROI 1
- `RBC_tiny_deskewed_output_1_ROI_0.csv`: `some_dict`, as a data frame, for ROI 1
- `RBC_tiny_deskewed_output_2_ROI_0.csv`: `some_list`, as a data frame, for ROI 1 
- `RBC_tiny_deskewed_output_3_ROI_0.csv`: `some_int`, as a data frame, for ROI 1 
- `RBC_tiny_deskewed_ROI_1.h5`: image for ROI 2
- `RBC_tiny_deskewed_output_1_ROI_1.csv`: `some_dict`, as a data frame, for ROI 2
- `RBC_tiny_deskewed_output_2_ROI_1.csv`:  `some_list`, as a data frame, for ROI 2
- `RBC_tiny_deskewed_output_3_ROI_1.csv`: `some_int`, as a data frame, for ROI 2

**Review by pr4deepr — CHANGES_REQUESTED** [review]
It is working as intended, but I have another issue now:

- When running cropping only, each ROI is saved individually (this is what we want)
- When running cropping and a workflow, the images and tables are saved only after all ROIs are processed. 

I verified this in a new environment.. Similar to https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/issues/71

**Comment by multimeric** [comment]
I think this should be fixed now. Feel free to check.

**Comment by pr4deepr** [comment]
How did you fix it? I couldn't understand it from the commit..

**Comment by multimeric** [comment]
The key line is here: https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/blob/c6d295a3b6d8dba6c316c3655f37d535ff66e089/core/lls_core/models/lattice_data.py#L445-L449

Rather than running `workflow.get()` straight away which evaluates the workflow, I instead return a function with no arguments that will return its results. This lets the downstream code work the same, only it has to call `result.data()` to evaluate each output:
https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/blob/c6d295a3b6d8dba6c316c3655f37d535ff66e089/core/lls_core/models/results.py#L153

Most of the lazy evaluation I've written elsewhere uses generators, but in this case I couldn't return a generator, because we need to know the metadata for each slice so we can the slices by ROI. So in this case I return a list of lazily evaluated results instead of a lazily evaluated generator.

**Comment by pr4deepr** [comment]
It appears to be writing to disk as it processes the data, which is great!

However, the progress bar doesn't reflect the progress accurately. If there are multiple ROIs, the ROI progress bar will hit100% immediately and then wait for the entire processing to finish before exiting.. 
_The Time &channel progress bar are not shown.._

```
C:\Users\Public\Documents\Miniconda3\envs\napari_lattice_py310\lib\site-packages\pytools\persistent_dict.py:63: RecommendedHashNotFoundWarning: Unable to import recommended hash 'siphash24.siphash13', falling back to 'hashlib.sha256'. Run 'python3 -m pip install siphash24' to install the recommended hash.
  warn("Unable to import recommended hash 'siphash24.siphash13', "
C:\Users\Public\Documents\Miniconda3\envs\napari_lattice_py310\lib\site-packages\pydantic\_migration.py:283: UserWarning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:ValidationError`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
[INFO:2024-10-02 14:23:31,288] 1 custom modules imported
ROI: 100%|███████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 26.32it/s]
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels
Processing successful. Results can be found in
\saved
```
This happens only for Crop and Workflow. If its just Cropping, the progress bar works fine.

**Comment by pr4deepr** [comment]
Actually for Crop, when the processing is finished, the Time and Channel progress bar disappear and seem to be overwritten (?)

`ROI:   0%|                                                                                                                                         | 0/1 [00:00<?, ?it/s]INFO: blockdim levels (1) < subsamp levels (3): First-level block size (4, 256, 256) will be used for all levels                                    | 0/3 [00:00<?, ?it/s]
ROI: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:49<00:00, 49.93s/it]
Processing successful. Results can be found in \saved
`

**Comment by multimeric** [comment]
Replaced by #85.

**Pull request closed without merging**
